name: Build and Publish nuget package

on:
  workflow_dispatch:

env:
  FullVersion: 1.0.${{ github.run_number }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3

    - name: Run Tests
      run: dotnet test --configuration Release

    - name: Build nuget package
      run: dotnet pack --configuration Release -o nuget /p:Version=${{ env.FullVersion }}

    - name: Store artifact
      uses: actions/upload-artifact@v3
      with:
        name: package
        if-no-files-found: error
        path: nuget/TestableHttp.${{ env.FullVersion }}.nupkg

    - name: Publish nuget package
      run: dotnet nuget push nuget/TestableHttp.${{ env.FullVersion }}.nupkg --api-key "${{ secrets.nuget_api_key }}" --source https://api.nuget.org/v3/index.json


