name: Build and Publish nuget package

on:
  workflow_dispatch:

env:
  BaseVersion: 1.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3

    - name: Run Tests
      run: dotnet test --configuration Release

    - name: Build nuget package
      run: dotnet pack --configuration Release -o nuget /p:Version=${{ env.BaseVersion }}.${{ github.run_number }}

    - name: Store artifact
      uses: actions/upload-artifact@v3
      with:
        name: package
        if-no-files-found: error
        path: /nuget/TestableHttp.*.nupkg